services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: hrm-frontend
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    restart: unless-stopped
